// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6kVei6oEi6UgPmJXD7KY2JJFkLFZ-0J4',
    appId: '1:600270982113:web:c834a226322508d3d720a0',
    messagingSenderId: '600270982113',
    projectId: 'vaccine-scheduler-901ac',
    authDomain: 'vaccine-scheduler-901ac.firebaseapp.com',
    storageBucket: 'vaccine-scheduler-901ac.firebasestorage.app',
    measurementId: 'G-P8BGW9SBD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFO-GAD0UaWbHfflrZcuC-XeuM6GyQfMA',
    appId: '1:600270982113:android:1fc61847eb8ff025d720a0',
    messagingSenderId: '600270982113',
    projectId: 'vaccine-scheduler-901ac',
    storageBucket: 'vaccine-scheduler-901ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd7g2cadDxdsLD1FZMFl1QaIP3odduXkM',
    appId: '1:600270982113:ios:1c88ec5a9d35475bd720a0',
    messagingSenderId: '600270982113',
    projectId: 'vaccine-scheduler-901ac',
    storageBucket: 'vaccine-scheduler-901ac.firebasestorage.app',
    iosBundleId: 'com.example.vaccineScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd7g2cadDxdsLD1FZMFl1QaIP3odduXkM',
    appId: '1:600270982113:ios:1c88ec5a9d35475bd720a0',
    messagingSenderId: '600270982113',
    projectId: 'vaccine-scheduler-901ac',
    storageBucket: 'vaccine-scheduler-901ac.firebasestorage.app',
    iosBundleId: 'com.example.vaccineScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6kVei6oEi6UgPmJXD7KY2JJFkLFZ-0J4',
    appId: '1:600270982113:web:d63a3f7846e7645dd720a0',
    messagingSenderId: '600270982113',
    projectId: 'vaccine-scheduler-901ac',
    authDomain: 'vaccine-scheduler-901ac.firebaseapp.com',
    storageBucket: 'vaccine-scheduler-901ac.firebasestorage.app',
    measurementId: 'G-MHQ47W9LE3',
  );
}
